### ISSUE TITLE
Could you help upgrade the vulnerble dependency in object-detector

### ISSUE THREAD

**Issue by JoeGardner000** [ujjwalkar0/object_detector#2]
Hi, @ujjwalkar0 , I'd like to report a vulnerability issue in **object-detector_1.4**.
### Issue Description
I noticed that **object-detector_1.4** directly depends on **opencv-python_4.5.4.60**.
However, **opencv-python_4.5.4.60** sufferes from the vulnerabilites which the C libraries exposed as following dependency graph shows. Refer to [issue](https://github.com/opencv/opencv-python/issues/646).

### Dependency Graph between Python and Shared Libraries
![image (2)](https://user-images.githubusercontent.com/103017573/161751329-8eddde58-6bab-40ef-9096-cacf3211caf7.png)
### Suggested Vulnerability Patch Versions
**opencv-python** has upgraded these vulnerable C libraries to patch versions in release ***4.5.5.64***. 

Python build tools cannot report vulnerable C libraries, which may induce potential security issues to many downstream Python projects.
Could you please upgrade this vulnerable dependency?

Thanks for your help~
Best regards,
JoeGardner

**Comment by ujjwalkar0** [comment]
Thanks for the suggestion. I have resolved the issue in the latest version (object-detector_1.5)
